CREATE TABLE racing_history (
    entry_id BIGSERIAL PRIMARY KEY,
    date DATE NOT NULL,
    region VARCHAR(4) NOT NULL,
    course TEXT NOT NULL,
    race_id INTEGER NOT NULL,
    off TIME NOT NULL,
    race_name TEXT,
    type VARCHAR(7) NOT NULL,
    class VARCHAR(7),
    pattern VARCHAR(7),
    rating_band VARCHAR(7),
    age_band VARCHAR(6),
    sex_rest VARCHAR(5),
    dist TEXT NOT NULL,
    dist_f TEXT NOT NULL,
    going TEXT,
    surface VARCHAR(4),
    ran INTEGER NOT NULL,
    num INTEGER,
    pos VARCHAR(3) NOT NULL,
    draw VARCHAR(4),
    ovr_btn TEXT,
    btn TEXT,
    horse_id INTEGER NOT NULL,
    horse TEXT NOT NULL,
    age INTEGER NOT NULL,
    sex VARCHAR(1),
    lbs INTEGER NOT NULL,
    hg TEXT,
    time TEXT,
    dec_odds NUMERIC NOT NULL,
    jockey TEXT NOT NULL,
    trainer TEXT NOT NULL,
    prize NUMERIC,
    ofr TEXT,
    rpr TEXT,
    ts TEXT,
    sire_id INTEGER,
    sire TEXT,
    dam_id INTEGER,
    dam TEXT,
    damsire_id INTEGER,
    damsire TEXT,
    owner TEXT,
    silk_url TEXT,
    comment TEXT
)